from enum import StrEnum


class ToolStatus(StrEnum):
    COMPLETED = "completed"
    QUEUED = "queued"
    PROCESSING = "processing"
    NEEDS_INPUT = "needs_input"
    AUTH_REQUIRED = "auth_required"
    NEEDS_CONFIRMATION = "needs_confirmation"
    PARTIAL = "partial"
    FAILED = "failed"


class JobType(StrEnum):
    VALIDATE_LUMA_SESSION = "VALIDATE_LUMA_SESSION"
    DISCOVER_EVENTS = "DISCOVER_EVENTS"
    SYNC_EVENT_DETAILS = "SYNC_EVENT_DETAILS"
    SCRAPE_EVENT_GUESTS = "SCRAPE_EVENT_GUESTS"
    ENRICH_PERSON = "ENRICH_PERSON"
    ENRICH_COMPANY = "ENRICH_COMPANY"
    SCORE_EVENT = "SCORE_EVENT"
    SCORE_PERSON = "SCORE_PERSON"
    GENERATE_EVENT_REPORT = "GENERATE_EVENT_REPORT"
    AUTO_REGISTER_EVENT = "AUTO_REGISTER_EVENT"
    SEND_EVENT_DIGEST = "SEND_EVENT_DIGEST"
    SEND_REPORT_EMAIL = "SEND_REPORT_EMAIL"
    SEND_REGISTRATION_CONFIRMATION = "SEND_REGISTRATION_CONFIRMATION"
    CREATE_ZERO_NETWORKING_CARD = "CREATE_ZERO_NETWORKING_CARD"
